# Generated by Django 5.1.2 on 2024-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('cast', models.TextField(help_text='Enter cast names separated by commas')),
                ('poster', models.ImageField(upload_to='posters/')),
                ('language', models.CharField(choices=[('english', 'English'), ('malayalam', 'Malayalam'), ('hindi', 'Hindi'), ('tamil', 'Tamil')], max_length=255)),
                ('category', models.CharField(choices=[('action', 'Action'), ('thriller', 'Thriller'), ('comedy', 'Comedy'), ('romantic', 'Romantic')], max_length=255)),
            ],
        ),
    ]
