# Generated by Django 5.1.2 on 2024-11-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EVM', 'EVM'), ('PVR', 'PVR'), ('CINEPOLIS', 'CINEPOLIS'), ('G CINEMAS', 'G CINEMAS'), ('M CINEMAS', 'M CINEMAS'), ('K CINEMAS', 'K CINEMAS')], max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('ACTION', 'Action'), ('THRILLER', 'Thriller'), ('COMEDY', 'Comedy'), ('ROMANTIC', 'Romantic')], max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('MALAYALAM', 'Malayalam'), ('HINDI', 'Hindi'), ('TAMIL', 'Tamil')], max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='theaters',
            field=models.ManyToManyField(related_name='movies', to='movies.theater'),
        ),
    ]
