# Generated by Django 5.1.2 on 2024-11-12 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 8, 48, 23, 40861, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
