# Generated by Django 5.1.2 on 2024-11-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_booking_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
    ]
