# Generated by Django 5.1.2 on 2024-11-15 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0012_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=255, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField(null=True)),
                ('event_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
